MTK: graphics: Update libgui_ext
Error was:

In file included from device/xiaomi/hermes/mtk/graphics/gui_ext/lib/GuiExtImpl.cpp:32:
device/xiaomi/hermes/mtk/graphics/gui_ext/lib/GuiExtImpl.h:90:53: warning: unused parameter 'item' [-Wunused-parameter]
    virtual void onFrameAvailable(const BufferItem& item) {};
                                                    ^
device/xiaomi/hermes/mtk/graphics/gui_ext/lib/GuiExtImpl.cpp:599:70: error: too few arguments to function call, expected 8, have 7
        producer->dequeueBuffer(&buf, &fence, 0, 0, fmt, usg, nullptr); // TODO:check if outTimestamps is required

~~~~~~~~~~~~~~~~~~~~~~~                                      ^
frameworks/native/libs/gui/include/gui/IGraphicBufferProducer.h:197:5: note: 'dequeueBuffer' declared here
    virtual status_t dequeueBuffer(int* slot, sp<Fence>* fence, uint32_t w, uint32_t h,
    ^
device/xiaomi/hermes/mtk/graphics/gui_ext/lib/GuiExtImpl.cpp:670:91: error: too few arguments to function call, expected 8, have 7
    status_t ret = producer->dequeueBuffer(buf, &fence, 0, 0, fmt, LOCK_FOR_USAGE, nullptr);
                   ~~~~~~~~~~~~~~~~~~~~~~~                                                ^

Signed-off-by: bilux <i.bilux@gmail.com>